server.ssl.key-store-type=PKCS12
server.ssl.key-store=${KEYSTORE_FILE}
server.ssl.key-store-password=${KEYSTORE_PASS}
server.ssl.key-alias=${KEYSTORE_ALIAS}
jwtgenerator.secret-key=${JWT_SECRET_KEY}

logging.file.name=${LOG}/ingestor.log


spring.data.mongodb.host=${MONGO_HOST}
spring.data.mongodb.port=${MONGO_PORT}
#spring.data.mongodb.authentication-database=admin
#spring.data.mongodb.username=<username specified on MONGO_INITDB_ROOT_USERNAME>
#spring.data.mongodb.password=<password specified on MONGO_INITDB_ROOT_PASSWORD>
spring.data.mongodb.database=systechlist


#spring.datasource.url=jdbc:h2:c:/$listasfiles/ingestordb
spring.datasource.url=jdbc:h2:mem
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=false

spring.batch.jdbc.initialize-schema=always
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.batch.job.enabled=false

batch.size=${BATCH_SIZE}

#A las 00:00:00 de todos los d�as menos el primero de mes
batch.cron.nocompare=${BATCH_CRON_NOCOMPARE}
#A las 00:00:00 de todos los d�as primero de mes
batch.cron.comparing=${BATCH_CRON_COMPARING}

download.buffersize=${DOWNLOAD_BUFFERSIZE}
download.timeout=${DOWNLOAD_TIMEOUT}

index.folder=${INDEX_FOLDER}
matcher.stopwords-file=${MATCHER_STOPWORDS_FILE}



#WC
mapping.id=${MAPPING_ID}
mapping.src-url=${MAPPING_SRC_URL}
mapping.working-dir=${MAPPING_WORKING_DIR}
mapping.file-name=${MAPPING_FILENAME}
mapping.name=${MAPPING_NAME}
mapping.delimiter=${MAPPING_DELIMITER}
mapping.quote=${MAPPING_QUOTE}
mapping.null=${MAPPING_NULL}
mapping.separator=${MAPPING_SEPARATOR}
mapping.errors.ignore=${MAPPING_ERRORS_IGNORE}
mapping.errors.max=${MAPPING_ERRORS_MAX}
mapping.save.history=${MAPPING_SAVE_HISTORY}
mapping.fields=age:Age,\
	age_date:AGE DATE (AS OF DATE),\
	aliases:Aliases,\
	alternative_spellings:ALTERNATIVE SPELLING,\
	category:Category,\
	companies:Companies,\
	countries:Countries,\
	deceased:Deceased,\
	dob:DOB,\
	e_i:E/I,\
	editor:Editor,\
	entered:Entered:yyyy/MM/dd,\
	updated:Updated:yyyy/MM/dd,\
	external_sources:EXTERNAL SOURCES,\
	further_information:Further Information,\
	ssn:SSN,\
	passports:Passports,\
	ids:IDENTIFICATION NUMBERS,\
	keywords:Keywords,\
	linked_to:Linked To,\
	locations:Locations,\
	firstname:First Name,\
	lastname:Last Name,\
	pob:PLACE OF BIRTH,\
	social_position:Position,\
	subcategory:Sub-Category,\
	title:Title,\
	ui:UID

