server.ssl.key-store-type=PKCS12
server.ssl.key-store=${KEYSTORE_FILE}
server.ssl.key-store-password=${KEYSTORE_PASS}
server.ssl.key-alias=${KEYSTORE_ALIAS}
jwtgenerator.secret-key=${JWT_SECRET_KEY}



logging.file.name=${LOG}/ingestor.log

server.port=8086
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
#spring.data.mongodb.authentication-database=admin
#spring.data.mongodb.username=<username specified on MONGO_INITDB_ROOT_USERNAME>
#spring.data.mongodb.password=<password specified on MONGO_INITDB_ROOT_PASSWORD>
spring.data.mongodb.database=systechlist


#spring.datasource.url=jdbc:h2:c:/$listasfiles/ingestordb
spring.datasource.url=jdbc:h2:mem
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=false

spring.batch.jdbc.initialize-schema=always
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.batch.job.enabled=false

batch.size=10000

#A las 00:00:00 de todos los d�as menos el primero de mes
batch.cron.nocompare=0 0 0 2-31 * *
#A las 00:00:00 de todos los d�as primero de mes
batch.cron.comparing=0 0 0 1 * *

download.buffersize=65536
download.timeout=60000

index.folder=c:/$listasfiles/lucene-index
matcher.stopwords-file=c:/$listas/stopwords/stopwords.txt



#WC
# mapping.id=WC
# mapping.src-url=https://ussyst0001:JAroca6108c@www.world-check.com/portal/Downloads/world-check.csv.gz
# mapping.working-dir=c:/$listasfiles/download
# mapping.file-name=WC.csv
# mapping.name=world-check
# mapping.delimiter=\t
# mapping.quote=
# mapping.null=-
# mapping.separator=;
# mapping.errors.ignore=true
# mapping.errors.max=20
# mapping.save.history=true
# mapping.fields=age:Age,\
# 	age_date:AGE DATE (AS OF DATE),\
# 	aliases:Aliases,\
# 	alternative_spellings:ALTERNATIVE SPELLING,\
# 	category:Category,\
# 	companies:Companies,\
# 	countries:Countries,\
# 	deceased:Deceased,\
# 	dob:DOB,\
# 	e_i:E/I,\
# 	editor:Editor,\
# 	entered:Entered:yyyy/MM/dd,\
# 	updated:Updated:yyyy/MM/dd,\
# 	external_sources:EXTERNAL SOURCES,\
# 	further_information:Further Information,\
# 	ssn:SSN,\
# 	passports:Passports,\
# 	ids:IDENTIFICATION NUMBERS,\
# 	keywords:Keywords,\
# 	linked_to:Linked To,\
# 	locations:Locations,\
# 	firstname:First Name,\
# 	lastname:Last Name,\
# 	pob:PLACE OF BIRTH,\
# 	social_position:Position,\
# 	subcategory:Sub-Category,\
# 	title:Title,\
# 	ui:UID


#SY
mapping.id=SY
mapping.src-url=ftp://SMG:$SMG605@ftplocal.systechsa.com/LISTAS_CSV.zip
mapping.working-dir=c:\\$listasfiles\\download
mapping.file-name=TB_WC_RECORDS.txt
mapping.name=systech
mapping.delimiter=;
mapping.separator=;
mapping.quote="
mapping.null=-
mapping.errors.ignore=true
mapping.errors.max=2000000000
mapping.save.history=true
mapping.fields=\
	aliases:Aliases,\
	alternative_spellings:AlternativeSpelling,\
	category:Category,\
	companies:companies,\
	countries:countries,\
	deceased:deceased,\
	deprecated_since:DateDeleted,\
	dob:DOB,\
	e_i:E_I,\
	editor:editor,\
	entered:entered:MMM dd yyyy hhmm:ENGLISH,\
	further_information:FurtherInformation,\
	ssn:SSN,\
	passports:passports,\
	keywords:keywords,\
	linked_to:linkedto,\
	locations:Locations,\
	firstname:FirstName,\
	lastname:LastName,\
	pob:POB,\
	social_position:SocialPosition,\
	subcategory:SubCategory,\
	title:Title,\
	updated:updated:MMM dd yyyy hhmm:ENGLISH,\
	ui:UI



