logging.file.name=${LOG}/retriever.log

spring.data.mongodb.host=${MONGO_HOST}
spring.data.mongodb.port=${MONGO_PORT}
spring.data.mongodb.database=${MONGO_DATABASE}
#spring.data.mongodb.authentication-database=${MONGO_AUTHENTICATION_DATABASE}
#spring.data.mongodb.username=${MONGO_USERNAME}
#spring.data.mongodb.password=${MONGO_PASSWORD}


jwtgenerator.secret-key=${JWT_SECRET_KEY}


server.ssl.key-store-type=PKCS12
server.ssl.key-store=${KEYSTORE_FILE}
server.ssl.key-store-password=${KEYSTORE_PASS}
server.ssl.key-alias=${KEYSTORE_ALIAS}



