server.port=8084
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
#spring.data.mongodb.authentication-database=admin
#spring.data.mongodb.username=<username specified on MONGO_INITDB_ROOT_USERNAME>
#spring.data.mongodb.password=<password specified on MONGO_INITDB_ROOT_PASSWORD>
spring.data.mongodb.database=systechlist

jwtgenerator.secret-key=${JWT_SECRET_KEY}

#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

server.ssl.key-store-type=PKCS12
server.ssl.key-store=${KEYSTORE_FILE}
server.ssl.key-store-password=${KEYSTORE_PASS}
server.ssl.key-alias=${KEYSTORE_ALIAS}
