logging.file.name=${LOG}/searcher.log

spring.data.mongodb.host=${MONGO_HOST}
spring.data.mongodb.port=${MONGO_PORT}
spring.data.mongodb.database=${MONGO_DATABASE}
#spring.data.mongodb.authentication-database=${MONGO_AUTHENTICATION_DATABASE}
#spring.data.mongodb.username=${MONGO_USERNAME}
#spring.data.mongodb.password=${MONGO_PASSWORD}


jwtgenerator.secret-key=${JWT_SECRET_KEY}

matcher.indexpath=${MATCHER_INDEXPATH}
matcher.stopwords-file=${MATCHER_STOPWORDS_FILE}
matcher.look-for-changes-in-index.cron=${MATCHER_LOOK_FOR_CHANGES_IN_INDEX_CRON}


server.ssl.key-store-type=PKCS12
server.ssl.key-store=${KEYSTORE_FILE}
server.ssl.key-store-password=${KEYSTORE_PASS}
server.ssl.key-alias=${KEYSTORE_ALIAS}


biller.url=${BILLER_URL}

systech.api-key=${SYSTECH-API-KEY}



